### get all blogs
GET http://localhost:3001/api/blogs

### post a blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Example Domain",
    "author": "example",
    "url": "http://example.com",
    "likes": 87
}

### get a unknownEndpoint
GET http://localhost:3003/unknownEndpointTest