### get all blogs
GET http://localhost:3001/api/blogs

### post a blog
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVydXNlciIsImlkIjoiNjA5OWYxODlkMjRhZTRkN2JkODMwYzYxIiwiaWF0IjoxNjIwNzE1MDAzLCJleHAiOjE2MjA3MTg2MDN9.o78aibHW19ZREhupa6ChFKzKhwU6RY5S1lh_BwOouF0

{
    "title": "Example Domain",
    "author": "example",
    "url": "http://example.com",
    "likes": 87
}


### delete a blog
DELETE  http://localhost:3001/api/blogs/<id>


### patch a blog
PATCH   http://localhost:3001/api/blogs/<id>
Content-Type: application/json

{
    "likes": 9999999
}


### get a unknownEndpoint
GET http://localhost:3003/unknownEndpointTest