### get all notes
GET http://localhost:3001/api/notes

### get a note
GET http://localhost:3001/api/notes/6040015fbb0538a49b06f690

### post a note
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "REST client request",
    "important": false
}

### content missing
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "",
    "important": true
}

### delete a note
DELETE http://localhost:3001/api/notes/6040015fbb0538a49b06f690

### put a note
PUT http://localhost:3001/api/notes/6040015fbb0538a49b06f690
Content-Type: application/json

{
    "content": "REST client request...",
    "important": true
}

### get a unknownEndpoint
GET http://localhost:3001/unknownEndpointTest