GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/6040015fbb0538a49b06f690

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "REST client request",
    "important": false
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "",
    "important": true
}

###
DELETE http://localhost:3001/api/notes/6040015fbb0538a49b06f690

###
PUT http://localhost:3001/api/notes/6040015fbb0538a49b06f690
Content-Type: application/json

{
    "content": "REST client request...",
    "important": true
}

###
GET http://localhost:3001/unknownEndpointTest