GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/1

###
DELETE http://localhost:3001/api/notes/1

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "REST client request",
    "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "",
    "important": true
}


###
GET http://localhost:3001/unknownEndpointTest