### GET all persons
GET http://localhost:3001/api/persons

### GET one person(exists)
GET http://localhost:3001/api/persons/<id>

### GET one person(not exist)
GET http://localhost:3001/api/persons/0

### DELETE one person
DELETE http://localhost:3001/api/persons/<id>

### POST one person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mark",
    "number": "0000-000-000"
}

### POST one person(Duplicate name)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mark Peng",
    "number": "12345"
}

### POST one person(no name error)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "0000-000-000"
}

### POST one person(no number error)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mark",
    "number": ""
}

### Patch one person number
PATCH http://localhost:3001/api/persons/<id>
Content-Type: application/json

{
    "number": "12345"
}

### Patch one person number (id error)
PATCH http://localhost:3001/api/persons/<id>
Content-Type: application/json

{
    "number": "12345"
}

